# Generated by Django 4.2.7 on 2023-11-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('download_link', models.URLField()),
            ],
        ),
    ]
