# Generated by Django 4.2.7 on 2023-11-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LetsStudyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(default='classic', max_length=200),
        ),
    ]
