# Generated by Django 4.2.7 on 2023-11-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LetsStudyApp', '0002_book_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('university_name', models.CharField(max_length=100)),
                ('university_location', models.CharField(max_length=255)),
                ('major_name', models.CharField(max_length=100)),
            ],
        ),
    ]
